package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * CatalagosOtrosId generated by hbm2java
 */
public class CatalagosOtrosId  implements java.io.Serializable {


     private int idOtro;
     private String sku;
     private String tabla;

    public CatalagosOtrosId() {
    }

    public CatalagosOtrosId(int idOtro, String sku, String tabla) {
       this.idOtro = idOtro;
       this.sku = sku;
       this.tabla = tabla;
    }
   
    public int getIdOtro() {
        return this.idOtro;
    }
    
    public void setIdOtro(int idOtro) {
        this.idOtro = idOtro;
    }
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CatalagosOtrosId) ) return false;
		 CatalagosOtrosId castOther = ( CatalagosOtrosId ) other; 
         
		 return (this.getIdOtro()==castOther.getIdOtro())
 && ( (this.getSku()==castOther.getSku()) || ( this.getSku()!=null && castOther.getSku()!=null && this.getSku().equals(castOther.getSku()) ) )
 && ( (this.getTabla()==castOther.getTabla()) || ( this.getTabla()!=null && castOther.getTabla()!=null && this.getTabla().equals(castOther.getTabla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOtro();
         result = 37 * result + ( getSku() == null ? 0 : this.getSku().hashCode() );
         result = 37 * result + ( getTabla() == null ? 0 : this.getTabla().hashCode() );
         return result;
   }   


}


