package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * CategoriasPrincipalesId generated by hbm2java
 */
public class CategoriasPrincipalesId  implements java.io.Serializable {


     private String categoria;
     private String subCategoria;
     private String subCategoriaArticulo;

    public CategoriasPrincipalesId() {
    }

    public CategoriasPrincipalesId(String categoria, String subCategoria, String subCategoriaArticulo) {
       this.categoria = categoria;
       this.subCategoria = subCategoria;
       this.subCategoriaArticulo = subCategoriaArticulo;
    }
   
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getSubCategoria() {
        return this.subCategoria;
    }
    
    public void setSubCategoria(String subCategoria) {
        this.subCategoria = subCategoria;
    }
    public String getSubCategoriaArticulo() {
        return this.subCategoriaArticulo;
    }
    
    public void setSubCategoriaArticulo(String subCategoriaArticulo) {
        this.subCategoriaArticulo = subCategoriaArticulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoriasPrincipalesId) ) return false;
		 CategoriasPrincipalesId castOther = ( CategoriasPrincipalesId ) other; 
         
		 return ( (this.getCategoria()==castOther.getCategoria()) || ( this.getCategoria()!=null && castOther.getCategoria()!=null && this.getCategoria().equals(castOther.getCategoria()) ) )
 && ( (this.getSubCategoria()==castOther.getSubCategoria()) || ( this.getSubCategoria()!=null && castOther.getSubCategoria()!=null && this.getSubCategoria().equals(castOther.getSubCategoria()) ) )
 && ( (this.getSubCategoriaArticulo()==castOther.getSubCategoriaArticulo()) || ( this.getSubCategoriaArticulo()!=null && castOther.getSubCategoriaArticulo()!=null && this.getSubCategoriaArticulo().equals(castOther.getSubCategoriaArticulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCategoria() == null ? 0 : this.getCategoria().hashCode() );
         result = 37 * result + ( getSubCategoria() == null ? 0 : this.getSubCategoria().hashCode() );
         result = 37 * result + ( getSubCategoriaArticulo() == null ? 0 : this.getSubCategoriaArticulo().hashCode() );
         return result;
   }   


}


