package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * CategoriasPrincipales generated by hbm2java
 */
public class CategoriasPrincipales  implements java.io.Serializable {


     private CategoriasPrincipalesId id;
     private String categoriaAbrev;
     private String subCategoriaAbrev;
     private String subCategoriaArticuloAbrev;
     private Double pesoAmbiental;
     private Double pesoEnvio;

    public CategoriasPrincipales() {
    }

	
    public CategoriasPrincipales(CategoriasPrincipalesId id) {
        this.id = id;
    }
    public CategoriasPrincipales(CategoriasPrincipalesId id, String categoriaAbrev, String subCategoriaAbrev, String subCategoriaArticuloAbrev, Double pesoAmbiental, Double pesoEnvio) {
       this.id = id;
       this.categoriaAbrev = categoriaAbrev;
       this.subCategoriaAbrev = subCategoriaAbrev;
       this.subCategoriaArticuloAbrev = subCategoriaArticuloAbrev;
       this.pesoAmbiental = pesoAmbiental;
       this.pesoEnvio = pesoEnvio;
    }
   
    public CategoriasPrincipalesId getId() {
        return this.id;
    }
    
    public void setId(CategoriasPrincipalesId id) {
        this.id = id;
    }
    public String getCategoriaAbrev() {
        return this.categoriaAbrev;
    }
    
    public void setCategoriaAbrev(String categoriaAbrev) {
        this.categoriaAbrev = categoriaAbrev;
    }
    public String getSubCategoriaAbrev() {
        return this.subCategoriaAbrev;
    }
    
    public void setSubCategoriaAbrev(String subCategoriaAbrev) {
        this.subCategoriaAbrev = subCategoriaAbrev;
    }
    public String getSubCategoriaArticuloAbrev() {
        return this.subCategoriaArticuloAbrev;
    }
    
    public void setSubCategoriaArticuloAbrev(String subCategoriaArticuloAbrev) {
        this.subCategoriaArticuloAbrev = subCategoriaArticuloAbrev;
    }
    public Double getPesoAmbiental() {
        return this.pesoAmbiental;
    }
    
    public void setPesoAmbiental(Double pesoAmbiental) {
        this.pesoAmbiental = pesoAmbiental;
    }
    public Double getPesoEnvio() {
        return this.pesoEnvio;
    }
    
    public void setPesoEnvio(Double pesoEnvio) {
        this.pesoEnvio = pesoEnvio;
    }




}


