package com.rropero.dto;
// Generated 12/09/2016 11:51:43 PM by Hibernate Tools 4.3.1



/**
 * CategoriasPrincipales generated by hbm2java
 */
public class CategoriasPrincipales  implements java.io.Serializable {


     private String categoria;
     private String categoriaAbrev;
     private String subCategoria;
     private String subCategoriaAbrev;
     private String subCategoriaArticulo;
     private String subCategoriaArticuloAbrev;
     private Double pesoAmbiental;
     private Double perosEnvio;

    public CategoriasPrincipales() {
    }

	
    public CategoriasPrincipales(String categoria) {
        this.categoria = categoria;
    }
    public CategoriasPrincipales(String categoria, String categoriaAbrev, String subCategoria, String subCategoriaAbrev, String subCategoriaArticulo, String subCategoriaArticuloAbrev, Double pesoAmbiental, Double perosEnvio) {
       this.categoria = categoria;
       this.categoriaAbrev = categoriaAbrev;
       this.subCategoria = subCategoria;
       this.subCategoriaAbrev = subCategoriaAbrev;
       this.subCategoriaArticulo = subCategoriaArticulo;
       this.subCategoriaArticuloAbrev = subCategoriaArticuloAbrev;
       this.pesoAmbiental = pesoAmbiental;
       this.perosEnvio = perosEnvio;
    }
   
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getCategoriaAbrev() {
        return this.categoriaAbrev;
    }
    
    public void setCategoriaAbrev(String categoriaAbrev) {
        this.categoriaAbrev = categoriaAbrev;
    }
    public String getSubCategoria() {
        return this.subCategoria;
    }
    
    public void setSubCategoria(String subCategoria) {
        this.subCategoria = subCategoria;
    }
    public String getSubCategoriaAbrev() {
        return this.subCategoriaAbrev;
    }
    
    public void setSubCategoriaAbrev(String subCategoriaAbrev) {
        this.subCategoriaAbrev = subCategoriaAbrev;
    }
    public String getSubCategoriaArticulo() {
        return this.subCategoriaArticulo;
    }
    
    public void setSubCategoriaArticulo(String subCategoriaArticulo) {
        this.subCategoriaArticulo = subCategoriaArticulo;
    }
    public String getSubCategoriaArticuloAbrev() {
        return this.subCategoriaArticuloAbrev;
    }
    
    public void setSubCategoriaArticuloAbrev(String subCategoriaArticuloAbrev) {
        this.subCategoriaArticuloAbrev = subCategoriaArticuloAbrev;
    }
    public Double getPesoAmbiental() {
        return this.pesoAmbiental;
    }
    
    public void setPesoAmbiental(Double pesoAmbiental) {
        this.pesoAmbiental = pesoAmbiental;
    }
    public Double getPerosEnvio() {
        return this.perosEnvio;
    }
    
    public void setPerosEnvio(Double perosEnvio) {
        this.perosEnvio = perosEnvio;
    }




}


