package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * EstadoPrenda generated by hbm2java
 */
public class EstadoPrenda  implements java.io.Serializable {


     private String estadoPrenda;
     private String estadoPrendaAbrev;
     private Double porcentajeDescuento;

    public EstadoPrenda() {
    }

	
    public EstadoPrenda(String estadoPrenda) {
        this.estadoPrenda = estadoPrenda;
    }
    public EstadoPrenda(String estadoPrenda, String estadoPrendaAbrev, Double porcentajeDescuento) {
       this.estadoPrenda = estadoPrenda;
       this.estadoPrendaAbrev = estadoPrendaAbrev;
       this.porcentajeDescuento = porcentajeDescuento;
    }
   
    public String getEstadoPrenda() {
        return this.estadoPrenda;
    }
    
    public void setEstadoPrenda(String estadoPrenda) {
        this.estadoPrenda = estadoPrenda;
    }
    public String getEstadoPrendaAbrev() {
        return this.estadoPrendaAbrev;
    }
    
    public void setEstadoPrendaAbrev(String estadoPrendaAbrev) {
        this.estadoPrendaAbrev = estadoPrendaAbrev;
    }
    public Double getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(Double porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }




}


