package com.rropero.dto;
// Generated 12/09/2016 11:51:43 PM by Hibernate Tools 4.3.1



/**
 * EstadoPrenda generated by hbm2java
 */
public class EstadoPrenda  implements java.io.Serializable {


     private String estadoPrenda;
     private Double porcentajeDescuento;

    public EstadoPrenda() {
    }

	
    public EstadoPrenda(String estadoPrenda) {
        this.estadoPrenda = estadoPrenda;
    }
    public EstadoPrenda(String estadoPrenda, Double porcentajeDescuento) {
       this.estadoPrenda = estadoPrenda;
       this.porcentajeDescuento = porcentajeDescuento;
    }
   
    public String getEstadoPrenda() {
        return this.estadoPrenda;
    }
    
    public void setEstadoPrenda(String estadoPrenda) {
        this.estadoPrenda = estadoPrenda;
    }
    public Double getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(Double porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }




}


