package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * Materiales generated by hbm2java
 */
public class Materiales  implements java.io.Serializable {


     private MaterialesId id;
     private Double peso;
     private Double densidad;
     private Double factorEnergia;
     private Double factorCo2;
     private Double usoAgua;

    public Materiales() {
    }

	
    public Materiales(MaterialesId id) {
        this.id = id;
    }
    public Materiales(MaterialesId id, Double peso, Double densidad, Double factorEnergia, Double factorCo2, Double usoAgua) {
       this.id = id;
       this.peso = peso;
       this.densidad = densidad;
       this.factorEnergia = factorEnergia;
       this.factorCo2 = factorCo2;
       this.usoAgua = usoAgua;
    }
   
    public MaterialesId getId() {
        return this.id;
    }
    
    public void setId(MaterialesId id) {
        this.id = id;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getDensidad() {
        return this.densidad;
    }
    
    public void setDensidad(Double densidad) {
        this.densidad = densidad;
    }
    public Double getFactorEnergia() {
        return this.factorEnergia;
    }
    
    public void setFactorEnergia(Double factorEnergia) {
        this.factorEnergia = factorEnergia;
    }
    public Double getFactorCo2() {
        return this.factorCo2;
    }
    
    public void setFactorCo2(Double factorCo2) {
        this.factorCo2 = factorCo2;
    }
    public Double getUsoAgua() {
        return this.usoAgua;
    }
    
    public void setUsoAgua(Double usoAgua) {
        this.usoAgua = usoAgua;
    }




}


