package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * MaterialesId generated by hbm2java
 */
public class MaterialesId  implements java.io.Serializable {


     private int idMaterial;
     private String categoriaMaterial;
     private String meterial;

    public MaterialesId() {
    }

    public MaterialesId(int idMaterial, String categoriaMaterial, String meterial) {
       this.idMaterial = idMaterial;
       this.categoriaMaterial = categoriaMaterial;
       this.meterial = meterial;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getCategoriaMaterial() {
        return this.categoriaMaterial;
    }
    
    public void setCategoriaMaterial(String categoriaMaterial) {
        this.categoriaMaterial = categoriaMaterial;
    }
    public String getMeterial() {
        return this.meterial;
    }
    
    public void setMeterial(String meterial) {
        this.meterial = meterial;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialesId) ) return false;
		 MaterialesId castOther = ( MaterialesId ) other; 
         
		 return (this.getIdMaterial()==castOther.getIdMaterial())
 && ( (this.getCategoriaMaterial()==castOther.getCategoriaMaterial()) || ( this.getCategoriaMaterial()!=null && castOther.getCategoriaMaterial()!=null && this.getCategoriaMaterial().equals(castOther.getCategoriaMaterial()) ) )
 && ( (this.getMeterial()==castOther.getMeterial()) || ( this.getMeterial()!=null && castOther.getMeterial()!=null && this.getMeterial().equals(castOther.getMeterial()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMaterial();
         result = 37 * result + ( getCategoriaMaterial() == null ? 0 : this.getCategoriaMaterial().hashCode() );
         result = 37 * result + ( getMeterial() == null ? 0 : this.getMeterial().hashCode() );
         return result;
   }   


}


