package com.rropero.dto;
// Generated 12/09/2016 11:51:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String sku;
     private Integer categoriaprincipal;
     private Integer subcategoriaprincipal;
     private Integer subcategoria;
     private String marca;
     private String talla;
     private Integer cliente;
     private Integer materia;
     private Date fechaentrega;
     private Date horaentrega;
     private Date fechaventa;
     private Date horaventa;
     private String estado;
     private String nombredelarticuloventa;
     private Integer categoriacalidad;
     private String descripcion;
     private Boolean shopify;
     private String modoentrega;
     private Double preciofinal;
     private Integer pesoproducto;
     private Integer pesoproductoenvio;
     private Integer existencia;

    public Producto() {
    }

	
    public Producto(String sku) {
        this.sku = sku;
    }
    public Producto(String sku, Integer categoriaprincipal, Integer subcategoriaprincipal, Integer subcategoria, String marca, String talla, Integer cliente, Integer materia, Date fechaentrega, Date horaentrega, Date fechaventa, Date horaventa, String estado, String nombredelarticuloventa, Integer categoriacalidad, String descripcion, Boolean shopify, String modoentrega, Double preciofinal, Integer pesoproducto, Integer pesoproductoenvio, Integer existencia) {
       this.sku = sku;
       this.categoriaprincipal = categoriaprincipal;
       this.subcategoriaprincipal = subcategoriaprincipal;
       this.subcategoria = subcategoria;
       this.marca = marca;
       this.talla = talla;
       this.cliente = cliente;
       this.materia = materia;
       this.fechaentrega = fechaentrega;
       this.horaentrega = horaentrega;
       this.fechaventa = fechaventa;
       this.horaventa = horaventa;
       this.estado = estado;
       this.nombredelarticuloventa = nombredelarticuloventa;
       this.categoriacalidad = categoriacalidad;
       this.descripcion = descripcion;
       this.shopify = shopify;
       this.modoentrega = modoentrega;
       this.preciofinal = preciofinal;
       this.pesoproducto = pesoproducto;
       this.pesoproductoenvio = pesoproductoenvio;
       this.existencia = existencia;
    }
   
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    public Integer getCategoriaprincipal() {
        return this.categoriaprincipal;
    }
    
    public void setCategoriaprincipal(Integer categoriaprincipal) {
        this.categoriaprincipal = categoriaprincipal;
    }
    public Integer getSubcategoriaprincipal() {
        return this.subcategoriaprincipal;
    }
    
    public void setSubcategoriaprincipal(Integer subcategoriaprincipal) {
        this.subcategoriaprincipal = subcategoriaprincipal;
    }
    public Integer getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Integer subcategoria) {
        this.subcategoria = subcategoria;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public Integer getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Integer cliente) {
        this.cliente = cliente;
    }
    public Integer getMateria() {
        return this.materia;
    }
    
    public void setMateria(Integer materia) {
        this.materia = materia;
    }
    public Date getFechaentrega() {
        return this.fechaentrega;
    }
    
    public void setFechaentrega(Date fechaentrega) {
        this.fechaentrega = fechaentrega;
    }
    public Date getHoraentrega() {
        return this.horaentrega;
    }
    
    public void setHoraentrega(Date horaentrega) {
        this.horaentrega = horaentrega;
    }
    public Date getFechaventa() {
        return this.fechaventa;
    }
    
    public void setFechaventa(Date fechaventa) {
        this.fechaventa = fechaventa;
    }
    public Date getHoraventa() {
        return this.horaventa;
    }
    
    public void setHoraventa(Date horaventa) {
        this.horaventa = horaventa;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getNombredelarticuloventa() {
        return this.nombredelarticuloventa;
    }
    
    public void setNombredelarticuloventa(String nombredelarticuloventa) {
        this.nombredelarticuloventa = nombredelarticuloventa;
    }
    public Integer getCategoriacalidad() {
        return this.categoriacalidad;
    }
    
    public void setCategoriacalidad(Integer categoriacalidad) {
        this.categoriacalidad = categoriacalidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getShopify() {
        return this.shopify;
    }
    
    public void setShopify(Boolean shopify) {
        this.shopify = shopify;
    }
    public String getModoentrega() {
        return this.modoentrega;
    }
    
    public void setModoentrega(String modoentrega) {
        this.modoentrega = modoentrega;
    }
    public Double getPreciofinal() {
        return this.preciofinal;
    }
    
    public void setPreciofinal(Double preciofinal) {
        this.preciofinal = preciofinal;
    }
    public Integer getPesoproducto() {
        return this.pesoproducto;
    }
    
    public void setPesoproducto(Integer pesoproducto) {
        this.pesoproducto = pesoproducto;
    }
    public Integer getPesoproductoenvio() {
        return this.pesoproductoenvio;
    }
    
    public void setPesoproductoenvio(Integer pesoproductoenvio) {
        this.pesoproductoenvio = pesoproductoenvio;
    }
    public Integer getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Integer existencia) {
        this.existencia = existencia;
    }




}


