package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String sku;
     private String categoria;
     private String subCategoria;
     private String subCategoriaArticulo;
     private String marca;
     private Integer idTalla;
     private Integer idCliente;
     private Integer idMaterial;
     private String estadoPrenda;
     private String categoriaEntrega;
     private Double precio;
     private Date fechaentrega;
     private String nombreArticulo;
     private Date fechaventa;
     private String descripcion;
     private Boolean shopify;
     private Double precioFinal;
     private Integer existencia;

    public Producto() {
    }

	
    public Producto(String sku) {
        this.sku = sku;
    }
    public Producto(String sku, String categoria, String subCategoria, String subCategoriaArticulo, String marca, Integer idTalla, Integer idCliente, Integer idMaterial, String estadoPrenda, String categoriaEntrega, Double precio, Date fechaentrega, String nombreArticulo, Date fechaventa, String descripcion, Boolean shopify, Double precioFinal, Integer existencia) {
       this.sku = sku;
       this.categoria = categoria;
       this.subCategoria = subCategoria;
       this.subCategoriaArticulo = subCategoriaArticulo;
       this.marca = marca;
       this.idTalla = idTalla;
       this.idCliente = idCliente;
       this.idMaterial = idMaterial;
       this.estadoPrenda = estadoPrenda;
       this.categoriaEntrega = categoriaEntrega;
       this.precio = precio;
       this.fechaentrega = fechaentrega;
       this.nombreArticulo = nombreArticulo;
       this.fechaventa = fechaventa;
       this.descripcion = descripcion;
       this.shopify = shopify;
       this.precioFinal = precioFinal;
       this.existencia = existencia;
    }
   
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getSubCategoria() {
        return this.subCategoria;
    }
    
    public void setSubCategoria(String subCategoria) {
        this.subCategoria = subCategoria;
    }
    public String getSubCategoriaArticulo() {
        return this.subCategoriaArticulo;
    }
    
    public void setSubCategoriaArticulo(String subCategoriaArticulo) {
        this.subCategoriaArticulo = subCategoriaArticulo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Integer getIdTalla() {
        return this.idTalla;
    }
    
    public void setIdTalla(Integer idTalla) {
        this.idTalla = idTalla;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getEstadoPrenda() {
        return this.estadoPrenda;
    }
    
    public void setEstadoPrenda(String estadoPrenda) {
        this.estadoPrenda = estadoPrenda;
    }
    public String getCategoriaEntrega() {
        return this.categoriaEntrega;
    }
    
    public void setCategoriaEntrega(String categoriaEntrega) {
        this.categoriaEntrega = categoriaEntrega;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFechaentrega() {
        return this.fechaentrega;
    }
    
    public void setFechaentrega(Date fechaentrega) {
        this.fechaentrega = fechaentrega;
    }
    public String getNombreArticulo() {
        return this.nombreArticulo;
    }
    
    public void setNombreArticulo(String nombreArticulo) {
        this.nombreArticulo = nombreArticulo;
    }
    public Date getFechaventa() {
        return this.fechaventa;
    }
    
    public void setFechaventa(Date fechaventa) {
        this.fechaventa = fechaventa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getShopify() {
        return this.shopify;
    }
    
    public void setShopify(Boolean shopify) {
        this.shopify = shopify;
    }
    public Double getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(Double precioFinal) {
        this.precioFinal = precioFinal;
    }
    public Integer getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Integer existencia) {
        this.existencia = existencia;
    }




}


