package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * RangoPrecio generated by hbm2java
 */
public class RangoPrecio  implements java.io.Serializable {


     private RangoPrecioId id;
     private Double precioPromedio;

    public RangoPrecio() {
    }

	
    public RangoPrecio(RangoPrecioId id) {
        this.id = id;
    }
    public RangoPrecio(RangoPrecioId id, Double precioPromedio) {
       this.id = id;
       this.precioPromedio = precioPromedio;
    }
   
    public RangoPrecioId getId() {
        return this.id;
    }
    
    public void setId(RangoPrecioId id) {
        this.id = id;
    }
    public Double getPrecioPromedio() {
        return this.precioPromedio;
    }
    
    public void setPrecioPromedio(Double precioPromedio) {
        this.precioPromedio = precioPromedio;
    }




}


