package com.rropero.dto;
// Generated 12/09/2016 11:51:43 PM by Hibernate Tools 4.3.1



/**
 * RangoPrecio generated by hbm2java
 */
public class RangoPrecio  implements java.io.Serializable {


     private String categoriaMarca;
     private String subCategoriaArticulo;
     private Double precioPromedio;

    public RangoPrecio() {
    }

	
    public RangoPrecio(String categoriaMarca) {
        this.categoriaMarca = categoriaMarca;
    }
    public RangoPrecio(String categoriaMarca, String subCategoriaArticulo, Double precioPromedio) {
       this.categoriaMarca = categoriaMarca;
       this.subCategoriaArticulo = subCategoriaArticulo;
       this.precioPromedio = precioPromedio;
    }
   
    public String getCategoriaMarca() {
        return this.categoriaMarca;
    }
    
    public void setCategoriaMarca(String categoriaMarca) {
        this.categoriaMarca = categoriaMarca;
    }
    public String getSubCategoriaArticulo() {
        return this.subCategoriaArticulo;
    }
    
    public void setSubCategoriaArticulo(String subCategoriaArticulo) {
        this.subCategoriaArticulo = subCategoriaArticulo;
    }
    public Double getPrecioPromedio() {
        return this.precioPromedio;
    }
    
    public void setPrecioPromedio(Double precioPromedio) {
        this.precioPromedio = precioPromedio;
    }




}


