package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * RangoPrecioId generated by hbm2java
 */
public class RangoPrecioId  implements java.io.Serializable {


     private String categoriaMarca;
     private String subCategoriaArticulo;

    public RangoPrecioId() {
    }

    public RangoPrecioId(String categoriaMarca, String subCategoriaArticulo) {
       this.categoriaMarca = categoriaMarca;
       this.subCategoriaArticulo = subCategoriaArticulo;
    }
   
    public String getCategoriaMarca() {
        return this.categoriaMarca;
    }
    
    public void setCategoriaMarca(String categoriaMarca) {
        this.categoriaMarca = categoriaMarca;
    }
    public String getSubCategoriaArticulo() {
        return this.subCategoriaArticulo;
    }
    
    public void setSubCategoriaArticulo(String subCategoriaArticulo) {
        this.subCategoriaArticulo = subCategoriaArticulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RangoPrecioId) ) return false;
		 RangoPrecioId castOther = ( RangoPrecioId ) other; 
         
		 return ( (this.getCategoriaMarca()==castOther.getCategoriaMarca()) || ( this.getCategoriaMarca()!=null && castOther.getCategoriaMarca()!=null && this.getCategoriaMarca().equals(castOther.getCategoriaMarca()) ) )
 && ( (this.getSubCategoriaArticulo()==castOther.getSubCategoriaArticulo()) || ( this.getSubCategoriaArticulo()!=null && castOther.getSubCategoriaArticulo()!=null && this.getSubCategoriaArticulo().equals(castOther.getSubCategoriaArticulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCategoriaMarca() == null ? 0 : this.getCategoriaMarca().hashCode() );
         result = 37 * result + ( getSubCategoriaArticulo() == null ? 0 : this.getSubCategoriaArticulo().hashCode() );
         return result;
   }   


}


