package com.rropero.dto;
// Generated 12/09/2016 11:51:43 PM by Hibernate Tools 4.3.1



/**
 * Tallas generated by hbm2java
 */
public class Tallas  implements java.io.Serializable {


     private String tipoMedida;
     private String talla;
     private String categoria;

    public Tallas() {
    }

	
    public Tallas(String tipoMedida) {
        this.tipoMedida = tipoMedida;
    }
    public Tallas(String tipoMedida, String talla, String categoria) {
       this.tipoMedida = tipoMedida;
       this.talla = talla;
       this.categoria = categoria;
    }
   
    public String getTipoMedida() {
        return this.tipoMedida;
    }
    
    public void setTipoMedida(String tipoMedida) {
        this.tipoMedida = tipoMedida;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }




}


