package com.rropero.dto;
// Generated 12/09/2016 11:51:43 PM by Hibernate Tools 4.3.1



/**
 * User1 generated by hbm2java
 */
public class User1  implements java.io.Serializable {


     private int idCliente;
     private String nombreCliente;
     private String EMail;

    public User1() {
    }

	
    public User1(int idCliente) {
        this.idCliente = idCliente;
    }
    public User1(int idCliente, String nombreCliente, String EMail) {
       this.idCliente = idCliente;
       this.nombreCliente = nombreCliente;
       this.EMail = EMail;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }




}


