package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * UsuarioLoginId generated by hbm2java
 */
public class UsuarioLoginId  implements java.io.Serializable {


     private int idCliente;
     private int idDatosCliente;

    public UsuarioLoginId() {
    }

    public UsuarioLoginId(int idCliente, int idDatosCliente) {
       this.idCliente = idCliente;
       this.idDatosCliente = idDatosCliente;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdDatosCliente() {
        return this.idDatosCliente;
    }
    
    public void setIdDatosCliente(int idDatosCliente) {
        this.idDatosCliente = idDatosCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioLoginId) ) return false;
		 UsuarioLoginId castOther = ( UsuarioLoginId ) other; 
         
		 return (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdDatosCliente()==castOther.getIdDatosCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdDatosCliente();
         return result;
   }   


}


