package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioDatos generated by hbm2java
 */
public class UsuarioDatos  implements java.io.Serializable {


     private int idDatosCliente;
     private String tipoCliente;
     private Set usuarioLogins = new HashSet(0);

    public UsuarioDatos() {
    }

	
    public UsuarioDatos(int idDatosCliente) {
        this.idDatosCliente = idDatosCliente;
    }
    public UsuarioDatos(int idDatosCliente, String tipoCliente, Set usuarioLogins) {
       this.idDatosCliente = idDatosCliente;
       this.tipoCliente = tipoCliente;
       this.usuarioLogins = usuarioLogins;
    }
   
    public int getIdDatosCliente() {
        return this.idDatosCliente;
    }
    
    public void setIdDatosCliente(int idDatosCliente) {
        this.idDatosCliente = idDatosCliente;
    }
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    public Set getUsuarioLogins() {
        return this.usuarioLogins;
    }
    
    public void setUsuarioLogins(Set usuarioLogins) {
        this.usuarioLogins = usuarioLogins;
    }




}


