package com.rropero.dto;
// Generated 17/09/2016 03:09:58 PM by Hibernate Tools 4.3.1



/**
 * UsuarioLogin generated by hbm2java
 */
public class UsuarioLogin  implements java.io.Serializable {


     private UsuarioLoginId id;
     private UsuarioDatos usuarioDatos;
     private String nombreCliente;
     private String EMail;
     private String pass;

    public UsuarioLogin() {
    }

	
    public UsuarioLogin(UsuarioLoginId id, UsuarioDatos usuarioDatos) {
        this.id = id;
        this.usuarioDatos = usuarioDatos;
    }
    public UsuarioLogin(UsuarioLoginId id, UsuarioDatos usuarioDatos, String nombreCliente, String EMail, String pass) {
       this.id = id;
       this.usuarioDatos = usuarioDatos;
       this.nombreCliente = nombreCliente;
       this.EMail = EMail;
       this.pass = pass;
    }
   
    public UsuarioLoginId getId() {
        return this.id;
    }
    
    public void setId(UsuarioLoginId id) {
        this.id = id;
    }
    public UsuarioDatos getUsuarioDatos() {
        return this.usuarioDatos;
    }
    
    public void setUsuarioDatos(UsuarioDatos usuarioDatos) {
        this.usuarioDatos = usuarioDatos;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


