--copy categorias_principales from 'C:\categorias_principales.csv' USING delimiters ',' ;
--copy materiales from 'C:\materiales.csv' USING delimiters ',' ;
--copy estado_prenda from 'C:\estadoPrenda.csv' USING delimiters ',' ;
--copy rango_precio from 'C:\rangoprecio.csv' USING delimiters ',' ;
--copy usuario_datos from 'C:\usuarios_datos.csv' USING delimiters ',' ;
--copy usuario_login from 'C:\usuarios_login.csv' USING delimiters ',' ;
--copy tallas from 'C:\Talla.csv' USING delimiters ',' ;