--copy categorias_principales from 'C:\categorias_principales.csv' USING delimiters ',' ;
--copy materiales from 'C:\materiales.csv' USING delimiters ',' ;
--copy estado_prenda from 'C:\estadoPrenda.csv' USING delimiters ',' ;
--copy rango_precio from 'C:\rangoprecio.csv' USING delimiters ',' ;